version: '3.8'

services:
  deepstream:
    build:
      context: .
      dockerfile: Dockerfile  # Ensure correct Dockerfile name if different
    runtime: nvidia
    environment:
      - DISPLAY=${DISPLAY}
      - DYNAMIC_PATH=${DYNAMIC_PATH}  # Pass DYNAMIC_PATH as an environment variable
    volumes:
      - /tmp/.X11-unix/:/tmp/.X11-unix
      - ${DYNAMIC_PATH}:/opt/nvidia/deepstream/deepstream-7.0/Deepstream  # Use DYNAMIC_PATH here
    network_mode: host
    stdin_open: true
    tty: true
